# Bybit 交易所分流规则 - Shadowrocket
# 更新时间: 2026-05-27

[Rule]
DOMAIN,bybit-exchange.github.io,PROXY,no-resolve
DOMAIN,app-measurement.com,PROXY,no-resolve
DOMAIN-SUFFIX,ffbbbdc6d3c353211fe2ba39c9f744cd.com,PROXY,no-resolve
DOMAIN-SUFFIX,ffe390afd658c19dcbf707e0597b846d.de,PROXY,no-resolve
DOMAIN-SUFFIX,amazon.com,PROXY,no-resolve
DOMAIN-SUFFIX,amazonaws.com,PROXY,no-resolve
DOMAIN-SUFFIX,bybit.biz,PROXY,no-resolve
DOMAIN-SUFFIX,bybit.com,PROXY,no-resolve
DOMAIN-SUFFIX,bycsi.com,PROXY,no-resolve
DOMAIN-SUFFIX,bytick.com,PROXY,no-resolve
DOMAIN-SUFFIX,byapis.com,PROXY,no-resolve
DOMAIN-SUFFIX,bycbe.com,PROXY,no-resolve
DOMAIN-SUFFIX,bymj.io,PROXY,no-resolve
DOMAIN-SUFFIX,byabcde.com,PROXY,no-resolve
DOMAIN-SUFFIX,byapps.net,PROXY,no-resolve
DOMAIN-SUFFIX,byd3c3.com,PROXY,no-resolve
DOMAIN-SUFFIX,bybdc6.com,PROXY,no-resolve
DOMAIN-SUFFIX,appsflyer.com,PROXY,no-resolve
IP-CIDR,13.32.121.6/32,PROXY,no-resolve
IP-CIDR,43.133.238.145/32,PROXY,no-resolve
IP-CIDR,13.33.187.108/32,PROXY,no-resolve
IP-CIDR,150.109.230.182/32,PROXY,no-resolve
IP-CIDR,142.251.215.234/32,PROXY,no-resolve
IP-CIDR,43.133.241.84/32,PROXY,no-resolve
IP-CIDR,3.160.150.37/32,PROXY,no-resolve
